services:
  server:
    build: 
      context: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app/
      - ./.vscode:/usr/src/app/server/.vscode
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    init: true
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
  db:
    image: postgres:17-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER"
      interval: 2s
      timeout: 5s
      retries: 5
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - ./.vscode:/app/client/.vscode
      - /app/client/node_modules
    env_file:
      - .env
    init: true

volumes:
  postgres:
